[workspace]
members = [
    "crates/giga-r1",
    "examples/dual_core_m4",
    "examples/dual_core_postcard_ipc/m4_worker",
    "examples/dual_core_postcard_ipc/m7_master",
    "examples/dual_core_postcard_ipc/protocol",
    "examples/dual_core_shared_queue/m4_worker",
    "examples/dual_core_shared_queue/m7_master",
    "examples/dual_core_shared_queue/protocol",
    "examples/m7_adc_read",
    "examples/m7_arduino_pins",
    "examples/m7_audio_process",
    "examples/m7_ble_beacon",
    "examples/m7_boot0_button",
    "examples/m7_dac_adc_loopback",
    "examples/m7_defmt_heartbeat",
    "examples/m7_dual_core_bridge",
    "examples/m7_exti_button",
    "examples/m7_fdcan_loopback",
    "examples/m7_gpio_loopback",
    "examples/m7_pwm_loopback",
    "examples/m7_qspi_blocking_storage",
    "examples/m7_qspi_jedec",
    "examples/m7_rgb_blinky",
    "examples/m7_spi_loopback",
    "examples/m7_uart_loopback",
    "examples/m7_usb_serial",
    "examples/m7_wifi_sdio_probe",
    "examples/m7_wifi_scan",
]
exclude = ["template"]
resolver = "2"

[workspace.package]
authors = ["Anapeksha Mukherjee <https://github.com/anapeksha>"]
homepage = "https://github.com/anapeksha/giga-r1-rs"
documentation = "https://docs.rs/giga-r1"
keywords = [
    "stm32h747",
    "embedded",
    "arduino",
    "giga",
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
license = "MIT"
repository = "https://github.com/anapeksha/giga-r1-rs"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embassy-futures = "0.1.2"
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
embassy-usb = "0.6.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-hal-nb = "1.0.0"
embedded-io-async = "0.7.0"
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"
nb = "1.1.0"
panic-halt = "1.0.0"
static_cell = "2.1.1"

[workspace.dependencies.cortex-m]
version = "0.7.7"
features = ["critical-section-single-core"]

[workspace.dependencies.cyw43]
version = "0.7.0"
default-features = false

[workspace.dependencies.embassy-executor]
version = "0.10.0"
default-features = false

[workspace.dependencies.embassy-stm32]
version = "0.6.0"
features = [
    "rt",
    "unstable-pac",
]
default-features = false

[workspace.dependencies.postcard]
version = "1.1.3"
default-features = false

[workspace.dependencies.serde]
version = "1.0.219"
default-features = false

[workspace.dependencies.trouble-host]
version = "0.7.0"
features = [
    "default-packet-pool",
    "peripheral",
]
default-features = false

[workspace.lints.clippy]
large_stack_frames = "deny"
mem_forget = "deny"

[workspace.lints.rust]
unsafe_code = "deny"
